### ISSUE TITLE
Can we use dotenv for ENV variables?

### ISSUE THREAD

**Issue by cloud8421** [MyMedsAndMe/marco_polo#15]
I can submit a PR for this, but just wanted to test the waters beforehand.

Would it be useful to use <https://github.com/avdi/dotenv_elixir> to manage environment variables in test?

**Comment by whatyouhide** [comment]
Hey @cloud8421,

I'm not familiar with dotenv_elixir, but I guess you'd want this to deal with the `ORIENTDB_USER` and `ORIENTDB_PASS` environment variables needed in tests, right?

**Comment by cloud8421** [comment]
Yes, that's exactly the reason why :)

**Comment by whatyouhide** [comment]
@cloud8421 so let me get this straight. We would use a `.env` file at the root of the repository with something like this in it:

```
ORIENTDB_USER=root
ORIENTDB_PASS=root
```

If I'm getting this right, we wouldn't check this into git because those variables can change for each user. This `.env` file would allow us to do `mix test` with these env variables setup in the test environment.

Am I correct?

**Comment by cloud8421** [comment]
You are. You usually gitignore .env, but commit a .env.example file with
dummy data so that a new user knows what env variables are needed.

**Comment by whatyouhide** [comment]
Added dotenv_elixir in 4ecd72c6aa47168d58008d105756821379d29db5! Thanks @cloud8421 :)
